### ISSUE TITLE
Code overlooks information gained by elimination

### ISSUE THREAD

**Issue by may42** [may42/my-console-project#1]
Некоторые шаги ошибочно принимаются за рискованные, потому что код не учитывает возможность игроков получить информацию о картах методом исключения. Для каждой карты на руках игроков следует создать 2 массива/словаря булевых значений, один для исключения возможных номиналов, другой для исключения возможных цветов.
Как организовать иерархию пока не знаю. Может быть вот так:

``` C#
public static bool[][] probableRank = new bool[5][];
public static Dictionary<Card.Colors,bool>[] probableColor=new Dictionary<Card.Colors,bool>[5];
for (int card = 0; card < 5; card++)
{
    probableRank[color] = new bool[5];
    probableColor[color] = Enum.GetValues(typeof(Colors)).Cast<Colors>()
                               .ToDictionary(t => t, t => false);
}
```

Или же оба сделать в виде двумерных массивов, и методов для работы с ними, вот уж не знаю... С этими Enum одни проблемы.

**Comment by SvorkHeiwa** [comment]
Ты намеренно сделал jagged-массив?

**Comment by may42** [comment]
Да, чтобы обращения были похожи, раз один - массив библиотек, то другой - массив массивов.

Может быть, стоит использовать два двумерных массива и использовать методы для работы с ними. Сейчас прямо сюда добавлю один из вариантов.

**Comment by SvorkHeiwa** [comment]
Вариант:
запилить классы RecievedRankInfo (в котором будет два Int32-свойства: с номером хода, на котором была получена инфа, и с номиналом карт, инфа о котором была получена) и RecievedColorInfo (Int32-свойство для номера хода, на котором была получена инфа и Card.Color-свойство, для описания цвета, о котором была получена инфа). В класс Player добавить два свойства с List'ами типов RecievedRankInfo и RecievedColorInfo и пополнять их в теле методов хода-подсказки. В класс CardOnHand добавить Int32-свойство для записи хода, на котором карта была получена.
В теле хода картой проверять инфу, полученную после взятия нужной карты. Если масть неизвестна, но были подсказки по 4-м мастям и/или номинал карты неизвестен, но были подсказки по 4-м номиналам, то ход не рискованный.

**Comment by may42** [comment]
Если колода очень-очень большая (много дубляжей карт маленьких номиналов, мало карт крупных номиналов) до List будет копиться впустую. А в случае с двумя bool-массивами в любой момент времени хранится не более 50 булевых значений на игрока.

**UPD:** Например, в твоём случае: лист Player.RecievedRankInfoHistory будет заполняться экземплярами класса RecievedRankInfo, и непонятно, когда нужно будет очищать этот лист от устаревших записей. Скажем, все пять карт на руках получены позднее 10го хода, а в листе всё ещё лежат записи информации, полученной на 1-10 ходах.

В среднем, за игру размером в 100 ходов происходит 12 подсказки ранга и 16 подсказок цвета (для каждого из игроков по-отдельности). Это значит что для такой игры суммарно накопится 28 экземпляров RecievedRankInfo / RecievedColorInfo.

**Comment by SvorkHeiwa** [comment]
Листы не для когоды, а дла игроков. У игрока не больше 5 карт в руках. И того 10 элементов листа для одного игрока.

**Comment by SvorkHeiwa** [comment]
Почему 50? 5(мастей)*5(номиналов) = 25.

**Comment by may42** [comment]
Один игрок, на руках пять карт, для каждой карты:
номинал-не-1: false
<...>
номинал-не-5: false
Итого для номиналов нужно хранить 5*5 булевых значений.
Таким образом, если игрок получит информацию "rank 1 for cards 0" то для карт с 1 по 4 будет записано:
номинал-не-1: true

**Comment by SvorkHeiwa** [comment]
Согласен, но даже в игре на тысячи ходов проверка не займёт и секунды.
И почему "50 булевых значений на игрока"? 5(мастей)*5(номиналов) = 25.

**Comment by may42** [comment]
Вот вариант с массивам и методами:

``` C#
class Player
{
    <...>
    pubic static bool[,] RankEliminationInfo = new bool[5,5];
    pubic static bool[,] ColorEliminationInfo = new bool[5,5];
```

В данный момент в методе `Player.GetColorInfo(bool[] cardsNumbers)` итерация цикла никак не обрабатывается, если в массиве под номером карты стоит False: `if (!cardsNumbers[i]) continue;`.
Я предлагаю в этой ветке присваивать `Player.ColorEliminationInfo[i,(int)color] = True;`
Но для этого придётся добавить этому методу параметр Colors color. Но этот вариант оптимален, даже не придётся создавать новые методы EliminateRank и EliminateColor.

Плюс я считаю, будет логичным методы GetCardsOfColor и GetCardsOfRank перенести из Game.cs в Player.cs.

А ещё надо бы внутри CardOnHand заменить Enum CardInfoAvaliabilities на два public bool поля RankIsKnown и ColorIsKnown. Это сильно упростит логику и вообще позволит избавиться от всего этого класса.

**Comment by may42** [comment]
> И почему "50 булевых значений на игрока"? 5(мастей)*5(номиналов) = 25.

Wtf? Я же писал тебе ответ на этот вопрос и ты удалил оба коммента. Ну и я удалил ответ, решив что ты понял.
